version : '3'

services :
  db :
    container_name : 'suthee-postgres'
    ports:
      - 54322:5432
    environment :
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image : 'postgres:14.4'
    restart : 'unless-stopped'
  pgadmin :
    container_name : 'suthee-pgadmin'
    ports:
      - 8079:80
    environment :
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASS}
    image : 'dpage/pgadmin4:latest'
    restart : 'unless-stopped'
  strapi :
    container_name : 'suthee-strapi'
    ports:
      - 1337:1337
    environment :
      - DATABASE_CLIENT=${D_CLIENT}
      - DATABASE_HOST=${D_HOST}
      - DATABASE_PORT=${D_PORT}
      - DATABASE_NAME=${D_NAME}
      - DATABASE_USERNAME=${D_USERNAME}
      - DATABASE_PASSWORD=${D_PASSWORD}
      - DATABASE_SSL=${D_SSL}
    image : 'naskio/strapi:latest'
    restart : 'unless-stopped'